name: Build and Release WikiStream

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]  # Runs only when a new GitHub Release is created

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.20.x, 1.21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Determine OS and Build
        run: |
          cd cmd
          case "${{ matrix.os }}" in
            ubuntu-latest) GOOS=linux ;;
            windows-latest) GOOS=windows ;;
            macos-latest) GOOS=darwin ;;
          esac
          GOARCH=amd64
          go build -o wikistream-$GOOS-amd64 main.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: wikistream-${{ matrix.os }}-${{ matrix.go-version }}
          path: cmd/wikistream-*

  release:
    name: Release Binaries
    needs: build
    if: github.event_name == 'release'  # Only runs if a GitHub Release is created
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/wikistream-*
          body: "binaries in case if it's not scaling"
