name: Build and Release WikiStream

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]  # Runs only when a new GitHub Release is created

jobs:
  build:
    name: Build for ${{ matrix.os }} with Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.18.x, 1.19.x, 1.20.x, 1.21.x]  # Updated to 4 Go versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: |
          cd cmd
          GOOS=$(echo "${{ matrix.os }}" | sed -e 's/ubuntu-latest/linux/' -e 's/windows-latest/windows/' -e 's/macos-latest/darwin/')
          GOARCH=amd64
          go build -o wikistream-$GOOS-amd64-go${{ matrix.go-version }} main.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: wikistream-${{ matrix.os }}-go${{ matrix.go-version }}
          path: cmd/wikistream-*

  release:
    name: Release Binaries
    needs: build
    if: github.event_name == 'release'  # Only runs if a GitHub Release is created
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wikistream-*/wikistream-*
          body: "binaries in case if it's not scaling"
